export const SUBJECTS = [
  { name: "AP Calculus AB", slug: "ap-calculus-ab", category: "Math" },
  { name: "AP Calculus BC", slug: "ap-calculus-bc", category: "Math" },
  { name: "AP Statistics", slug: "ap-statistics", category: "Math" },
  { name: "AP Biology", slug: "ap-biology", category: "Science" },
  { name: "AP Chemistry", slug: "ap-chemistry", category: "Science" },
  { name: "AP Physics 1", slug: "ap-physics-1", category: "Science" },
  { name: "AP Physics 2", slug: "ap-physics-2", category: "Science" },
  { name: "AP Physics C: Mechanics", slug: "ap-physics-c-mechanics", category: "Science" },
  { name: "AP Physics C: E&M", slug: "ap-physics-c-electricity-magnetism", category: "Science" },
  { name: "AP Environmental Science", slug: "ap-environmental-science", category: "Science" },
  { name: "AP US History", slug: "ap-us-history", category: "History" },
  { name: "AP World History", slug: "ap-world-history", category: "History" },
  { name: "AP European History", slug: "ap-european-history", category: "History" },
  { name: "AP Government", slug: "ap-us-government", category: "History" },
  { name: "AP Comparative Gov", slug: "ap-comparative-government", category: "History" },
  { name: "AP English Language", slug: "ap-english-language", category: "English" },
  { name: "AP English Literature", slug: "ap-english-literature", category: "English" },
  { name: "AP Psychology", slug: "ap-psychology", category: "Social Science" },
  { name: "AP Human Geography", slug: "ap-human-geography", category: "Social Science" },
  { name: "AP Macroeconomics", slug: "ap-macroeconomics", category: "Social Science" },
  { name: "AP Microeconomics", slug: "ap-microeconomics", category: "Social Science" },
  { name: "AP Computer Science A", slug: "ap-computer-science-a", category: "STEM" },
  { name: "AP Computer Science Principles", slug: "ap-computer-science-principles", category: "STEM" },
  { name: "AP Art History", slug: "ap-art-history", category: "Arts" },
  { name: "AP Music Theory", slug: "ap-music-theory", category: "Arts" },
  { name: "AP Studio Art", slug: "ap-studio-art", category: "Arts" },
  { name: "AP Spanish Language", slug: "ap-spanish-language", category: "Languages" },
  { name: "AP Spanish Literature", slug: "ap-spanish-literature", category: "Languages" },
  { name: "AP French Language", slug: "ap-french-language", category: "Languages" },
  { name: "AP German Language", slug: "ap-german-language", category: "Languages" },
  { name: "AP Latin", slug: "ap-latin", category: "Languages" },
  { name: "AP Chinese Language", slug: "ap-chinese-language", category: "Languages" },
  { name: "AP Japanese Language", slug: "ap-japanese-language", category: "Languages" },
  { name: "AP Italian Language", slug: "ap-italian-language", category: "Languages" },
  { name: "AP Capstone Research", slug: "ap-research", category: "Capstone" },
  { name: "AP Capstone Seminar", slug: "ap-seminar", category: "Capstone" },
];
