export interface SubjectConfig {
  slug: string;
  name: string;
  maxScore: number;
  mcqWeight: number;
  frqWeight: number;
  sections: {
    name: string;
    maxScore: number;
    description?: string;
  }[];
  scoringExplanation: string[];
  tips: {
    title: string;
    description: string;
  }[];
  faq: {
    question: string;
    answer: string;
  }[];
  relatedSubjects: string[];
}

export const SUBJECT_CONFIGS: { [key: string]: SubjectConfig } = {
  "ap-calculus-ab": {
    slug: "ap-calculus-ab",
    name: "AP Calculus AB",
    maxScore: 108,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ Part A (No Calculator)", maxScore: 30, description: "30 questions, 60 minutes" },
      { name: "MCQ Part B (Calculator)", maxScore: 15, description: "15 questions, 45 minutes" },
      { name: "FRQ 1", maxScore: 9, description: "Calculator active" },
      { name: "FRQ 2", maxScore: 9, description: "Calculator active" },
      { name: "FRQ 3", maxScore: 9, description: "No calculator" },
      { name: "FRQ 4", maxScore: 9, description: "No calculator" },
      { name: "FRQ 5", maxScore: 9, description: "No calculator" },
      { name: "FRQ 6", maxScore: 9, description: "No calculator" },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "Part A: 30 questions, no calculator, 60 minutes",
      "Part B: 15 questions, graphing calculator required, 45 minutes",
      "Section II: Free Response (50% of total score)",
      "6 questions, 90 minutes total",
      "Questions 1-2: calculator active",
      "Questions 3-6: calculator not permitted",
      "Your raw scores from both sections are combined into a composite score out of 108",
      "College Board converts this composite score to a 1-5 scale using a statistical curve",
    ],
    tips: [
      { title: "Master Limits and Continuity", description: "These concepts form the foundation for everything else. Make sure you can evaluate limits algebraically, graphically, and numerically." },
      { title: "Practice FRQ Format", description: "Free response questions follow predictable patterns. Practice writing complete solutions with proper justification, not just answers." },
      { title: "Know Your Calculator", description: "Part B and some FRQs require a graphing calculator. Be fluent with finding derivatives, integrals, and solving equations numerically." },
      { title: "Focus on Application Problems", description: "Related rates, optimization, and accumulation problems appear every year. Understand the setup, not just the computation." },
    ],
    faq: [
      { question: "What's the difference between Calculus AB and BC?", answer: "Calculus AB covers limits, derivatives, and basic integrals over one semester of college calculus. BC covers all AB topics plus parametric, polar, vector functions, and series — equivalent to two semesters." },
      { question: "Do I need a graphing calculator?", answer: "Yes. A graphing calculator is required for Part B of the multiple choice section and some free response questions. TI-84 or TI-Nspire series are recommended." },
      { question: "How hard is it to get a 5 on Calculus AB?", answer: "Historically, about 20-25% of students score a 5. Strong algebra skills and consistent practice with past FRQs are the best predictors of success." },
    ],
    relatedSubjects: ["ap-calculus-bc", "ap-statistics", "ap-physics-1", "ap-computer-science-a"],
  },

  "ap-calculus-bc": {
    slug: "ap-calculus-bc",
    name: "AP Calculus BC",
    maxScore: 108,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ Part A (No Calculator)", maxScore: 30 },
      { name: "MCQ Part B (Calculator)", maxScore: 15 },
      { name: "FRQ 1", maxScore: 9 },
      { name: "FRQ 2", maxScore: 9 },
      { name: "FRQ 3", maxScore: 9 },
      { name: "FRQ 4", maxScore: 9 },
      { name: "FRQ 5", maxScore: 9 },
      { name: "FRQ 6", maxScore: 9 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "Part A: 30 questions, no calculator, 60 minutes",
      "Part B: 15 questions, calculator required, 45 minutes",
      "Section II: Free Response (50% of total score)",
      "6 questions, 90 minutes",
      "Covers all AB topics plus parametric, polar, vector functions, and series",
      "Composite score out of 108, converted to 1-5 scale",
    ],
    tips: [
      { title: "Build on AB Foundation", description: "Make sure your AB knowledge is solid before tackling BC-specific topics. The BC exam includes all AB content." },
      { title: "Master Series Convergence", description: "Series and sequences are BC-only topics. Practice all convergence tests and know when to apply each one." },
      { title: "Parametric and Polar Fluency", description: "These question types appear on every BC exam. Practice finding derivatives, arc length, and areas in parametric/polar form." },
      { title: "Calculator Proficiency", description: "BC requires more advanced calculator skills including Euler's method, logistic growth, and Taylor polynomial approximations." },
    ],
    faq: [
      { question: "Is BC much harder than AB?", answer: "BC covers about 40% more content than AB, but the AB portion is identical. If you're strong in AB topics, the additional BC content is manageable with consistent practice." },
      { question: "Do colleges prefer BC over AB?", answer: "Many colleges grant credit for BC scores of 4-5 that covers two semesters of calculus, while AB typically covers only one. BC can place you into higher-level math courses." },
      { question: "Can I take BC without taking AB first?", answer: "Yes, many students do. BC is designed as a complete course that includes all AB material. Strong algebra and pre-calculus skills are essential." },
    ],
    relatedSubjects: ["ap-calculus-ab", "ap-physics-c-mechanics", "ap-statistics", "ap-computer-science-a"],
  },

  "ap-biology": {
    slug: "ap-biology",
    name: "AP Biology",
    maxScore: 120,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 60, description: "60 questions, 90 minutes" },
      { name: "FRQ 1 (Long)", maxScore: 10 },
      { name: "FRQ 2 (Long)", maxScore: 10 },
      { name: "FRQ 3 (Short)", maxScore: 4 },
      { name: "FRQ 4 (Short)", maxScore: 4 },
      { name: "FRQ 5 (Short)", maxScore: 4 },
      { name: "FRQ 6 (Short)", maxScore: 4 },
      { name: "FRQ 7 (Short)", maxScore: 4 },
      { name: "FRQ 8 (Short)", maxScore: 3 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "60 questions, 90 minutes, no calculator",
      "Section II: Free Response (50% of total score)",
      "2 long-form questions (10 points each)",
      "6 short-form questions (4 points each, except #8 at 3 points)",
      "90 minutes total",
      "Composite score out of 120, converted to 1-5 scale",
    ],
    tips: [
      { title: "Master the Four Big Ideas", description: "The entire AP Biology curriculum is organized around 4 big ideas: evolution, cellular processes, genetics, and ecology. Make sure you see connections between them." },
      { title: "Practice Graph Interpretation", description: "MCQs and FRQs both require reading graphs, charts, and experimental data. Practice interpreting trends and justifying conclusions with evidence." },
      { title: "Learn the Formula Sheet", description: "While you don't need to memorize every formula, you must know when and how to apply chi-square, Hardy-Weinberg, and water potential equations." },
      { title: "Write Like a Scientist", description: "FRQs are graded on scientific reasoning, not just answers. Use claim-evidence-reasoning structure and define all variables." },
    ],
    faq: [
      { question: "Is AP Biology mostly memorization?", answer: "No. While there is vocabulary to learn, the exam emphasizes reasoning, experimental design, and data analysis. Pure memorization alone won't get you a 4 or 5." },
      { question: "Do I need to know all the organelles?", answer: "Yes, but in context. The exam tests how organelles work together in cellular processes (respiration, photosynthesis, protein transport) rather than isolated facts." },
      { question: "How important is lab experience?", answer: "Very. The exam includes questions about lab techniques (gel electrophoresis, transformation, photosynthesis rates). Understanding the 'why' behind each lab is critical." },
    ],
    relatedSubjects: ["ap-chemistry", "ap-environmental-science", "ap-physics-1", "ap-psychology"],
  },

  "ap-chemistry": {
    slug: "ap-chemistry",
    name: "AP Chemistry",
    maxScore: 120,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 60, description: "60 questions, 90 minutes" },
      { name: "FRQ 1 (Long)", maxScore: 10 },
      { name: "FRQ 2 (Long)", maxScore: 10 },
      { name: "FRQ 3 (Long)", maxScore: 10 },
      { name: "FRQ 4 (Short)", maxScore: 4 },
      { name: "FRQ 5 (Short)", maxScore: 4 },
      { name: "FRQ 6 (Short)", maxScore: 4 },
      { name: "FRQ 7 (Short)", maxScore: 4 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "60 questions, 90 minutes, no calculator",
      "Covers all 9 units of the curriculum",
      "Section II: Free Response (50% of total score)",
      "3 long-form questions (10 points each)",
      "4 short-form questions (4 points each)",
      "105 minutes, calculator permitted",
      "Composite score out of 120",
    ],
    tips: [
      { title: "Master Unit Conversions", description: "Almost every calculation requires dimensional analysis. Practice converting between grams, moles, liters, and particles fluently and quickly." },
      { title: "Know Your Solubility Rules", description: "Precipitation reactions appear in both MCQ and FRQ. Memorize the common solubility rules to identify net ionic equations instantly." },
      { title: "Practice Lab-Based FRQs", description: "Several FRQs each year are based on laboratory procedures (titration, calorimetry, spectroscopy). Understand the purpose, procedure, and sources of error for each common lab." },
      { title: "Balance Redox in Acid/Base", description: "Redox reactions in acidic and basic solutions are a common FRQ topic. Practice the half-reaction method until you can balance them in under 3 minutes." },
    ],
    faq: [
      { question: "Do I need to memorize the periodic table?", answer: "You need to know trends (electronegativity, atomic radius, ionization energy) and common elements. The exam provides a periodic table, but you must know how to use it for predictions and calculations." },
      { question: "How much math is on the exam?", answer: "A significant amount. You'll calculate molar mass, stoichiometry, equilibrium constants, pH, and thermodynamics values. A scientific calculator is essential for the free response section." },
      { question: "What's the hardest unit?", answer: "Unit 8 (Acids and Bases) and Unit 9 (Applications of Thermodynamics) are typically the most challenging. Buffer solutions, titration curves, and Gibbs free energy calculations require strong conceptual understanding." },
    ],
    relatedSubjects: ["ap-biology", "ap-physics-1", "ap-environmental-science", "ap-physics-c-mechanics"],
  },

  "ap-physics-1": {
    slug: "ap-physics-1",
    name: "AP Physics 1",
    maxScore: 100,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ Part A", maxScore: 25, description: "25 questions, 45 minutes, no calculator" },
      { name: "MCQ Part B", maxScore: 20, description: "20 questions, 45 minutes, calculator" },
      { name: "FRQ 1 (Experimental Design)", maxScore: 12 },
      { name: "FRQ 2 (Qualitative/Quantitative)", maxScore: 12 },
      { name: "FRQ 3 (Paragraph Argument)", maxScore: 10 },
      { name: "FRQ 4 (Short Answer)", maxScore: 10 },
      { name: "FRQ 5 (Short Answer)", maxScore: 10 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "Part A: 25 questions, 45 minutes, no calculator",
      "Part B: 20 questions, 45 minutes, calculator permitted",
      "Section II: Free Response (50% of total score)",
      "5 questions, 90 minutes",
      "Question 1: Experimental Design (12 points)",
      "Question 2: Qualitative/Quantitative Translation (12 points)",
      "Question 3: Paragraph Argument Short Answer (10 points)",
      "Questions 4-5: Short Answer (10 points each)",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Draw Free-Body Diagrams", description: "Every mechanics problem starts with forces. Always sketch the situation, identify all forces, and choose a coordinate system before writing equations." },
      { title: "Master Conservation Laws", description: "Energy conservation and momentum conservation are tested on almost every exam. Know when each applies and how to set up the equations for complex systems." },
      { title: "Practice Without a Calculator", description: "Part A of the MCQ section is no-calculator. Practice estimating, using scientific notation, and doing algebra symbolically to build speed and confidence." },
      { title: "Write Complete FRQ Explanations", description: "Physics 1 FRQs award points for reasoning, not just answers. Explain 'why' using physics principles, and always include units in your final answers." },
    ],
    faq: [
      { question: "Is AP Physics 1 mostly math?", answer: "No. While algebra is required, the emphasis is on conceptual understanding, experimental design, and reasoning. Many questions test your ability to explain phenomena without heavy calculation." },
      { question: "Do I need to take Physics 1 before Physics C?", answer: "Not necessarily, but it helps. Physics 1 covers algebra-based mechanics and introduces key concepts. Physics C adds calculus and goes deeper into rotational motion and oscillations." },
      { question: "How important is lab experience?", answer: "Very. The Experimental Design FRQ (12 points) requires you to design a procedure, identify variables, and analyze data. Understanding common lab setups is essential." },
    ],
    relatedSubjects: ["ap-physics-2", "ap-physics-c-mechanics", "ap-calculus-ab", "ap-chemistry"],
  },

  "ap-physics-2": {
    slug: "ap-physics-2",
    name: "AP Physics 2",
    maxScore: 100,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 50 },
      { name: "FRQ 1", maxScore: 12 },
      { name: "FRQ 2", maxScore: 12 },
      { name: "FRQ 3", maxScore: 10 },
      { name: "FRQ 4", maxScore: 10 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "50 questions, 90 minutes",
      "Section II: Free Response (50% of total score)",
      "4 questions, 90 minutes",
      "Covers fluids, thermodynamics, electricity, magnetism, optics, and modern physics",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Review Physics 1 Concepts", description: "Physics 2 builds on Physics 1 foundations. Make sure your mechanics knowledge is solid before tackling new topics." },
      { title: "Master Circuit Analysis", description: "RC circuits and multi-loop circuits are common FRQ topics. Practice Kirchhoff's laws and understand how capacitors charge/discharge." },
      { title: "Understand Wave-Particle Duality", description: "Modern physics questions on the exam test your understanding of quantum mechanics, atomic structure, and nuclear physics at a conceptual level." },
      { title: "Practice Experimental Design", description: "Like Physics 1, the experimental design FRQ is critical. Be ready to design procedures for optics, thermodynamics, or electricity experiments." },
    ],
    faq: [
      { question: "Is Physics 2 harder than Physics 1?", answer: "Physics 2 covers more advanced topics and requires stronger algebra skills. The content is less intuitive than mechanics, so many students find it more challenging." },
      { question: "Do I need Physics 1 before Physics 2?", answer: "Yes, Physics 2 assumes knowledge of Physics 1 content. The College Board recommends completing Physics 1 first." },
      { question: "What's the hardest topic?", answer: "Electromagnetism and modern physics are typically the most challenging. These topics are less familiar to most students and require strong conceptual understanding." },
    ],
    relatedSubjects: ["ap-physics-1", "ap-physics-c-electricity-magnetism", "ap-calculus-ab", "ap-chemistry"],
  },

  "ap-physics-c-mechanics": {
    slug: "ap-physics-c-mechanics",
    name: "AP Physics C: Mechanics",
    maxScore: 90,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 35 },
      { name: "FRQ 1", maxScore: 15 },
      { name: "FRQ 2", maxScore: 15 },
      { name: "FRQ 3", maxScore: 15 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "35 questions, 45 minutes",
      "Section II: Free Response (50% of total score)",
      "3 questions, 45 minutes",
      "Calculus-based mechanics covering kinematics, dynamics, energy, momentum, and rotation",
      "Composite score out of 90",
    ],
    tips: [
      { title: "Calculus Fluency", description: "You must be comfortable with derivatives and integrals. Practice taking derivatives of position to get velocity/acceleration, and integrating force to find work." },
      { title: "Master Rotational Motion", description: "Rotational kinematics, torque, and angular momentum are heavily tested. Know the parallels between linear and rotational quantities." },
      { title: "Practice with Calculus", description: "Every problem should be solved using calculus when appropriate. Don't rely on kinematic equations when integration gives a more elegant solution." },
      { title: "Know Your Differential Equations", description: "Simple harmonic motion and other topics involve solving basic differential equations. Practice separating variables and integrating." },
    ],
    faq: [
      { question: "Do I need Calculus BC for Physics C?", answer: "No, AB is sufficient. You need basic derivatives and integrals, which are covered in AB. BC topics like series are not needed." },
      { question: "Is Physics C much harder than Physics 1?", answer: "Physics C covers similar mechanics topics but uses calculus and goes deeper. The math is more advanced, but the concepts are similar if you understand Physics 1." },
      { question: "How important is the calculus?", answer: "Essential. Every FRQ requires calculus-based solutions. You must set up and evaluate integrals for work, center of mass, and moment of inertia." },
    ],
    relatedSubjects: ["ap-physics-c-electricity-magnetism", "ap-calculus-bc", "ap-physics-1", "ap-calculus-ab"],
  },

  "ap-physics-c-electricity-magnetism": {
    slug: "ap-physics-c-electricity-magnetism",
    name: "AP Physics C: E&M",
    maxScore: 90,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 35 },
      { name: "FRQ 1", maxScore: 15 },
      { name: "FRQ 2", maxScore: 15 },
      { name: "FRQ 3", maxScore: 15 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "35 questions, 45 minutes",
      "Section II: Free Response (50% of total score)",
      "3 questions, 45 minutes",
      "Calculus-based electricity and magnetism",
      "Covers electrostatics, circuits, and magnetism",
      "Composite score out of 90",
    ],
    tips: [
      { title: "Master Gauss's Law", description: "Gauss's Law is fundamental to electrostatics. Practice choosing Gaussian surfaces and calculating electric fields for various charge distributions." },
      { title: "Understand RC and RL Circuits", description: "Transient analysis of circuits with capacitors and inductors requires solving differential equations. Practice the general solutions and time constants." },
      { title: "Visualize Magnetic Fields", description: "Use right-hand rules consistently. Draw field lines for current-carrying wires, loops, and solenoids to build intuition." },
      { title: "Connect E&M Concepts", description: "Maxwell's equations tie together electricity and magnetism. Understand how changing electric fields create magnetic fields and vice versa." },
    ],
    faq: [
      { question: "Should I take both Physics C exams?", answer: "Many students do. Mechanics is typically offered in fall, E&M in spring. Both together show strong physics preparation for engineering and physics majors." },
      { question: "How much calculus is used?", answer: "Extensive. You'll integrate charge distributions, evaluate line integrals for Ampere's law, and solve differential equations for circuits." },
      { question: "Is E&M harder than Mechanics?", answer: "Most students find E&M more abstract and challenging. The concepts are less intuitive than mechanics, and the calculus is more involved." },
    ],
    relatedSubjects: ["ap-physics-c-mechanics", "ap-calculus-bc", "ap-physics-2", "ap-calculus-ab"],
  },

  "ap-environmental-science": {
    slug: "ap-environmental-science",
    name: "AP Environmental Science",
    maxScore: 100,
    mcqWeight: 60,
    frqWeight: 40,
    sections: [
      { name: "MCQ", maxScore: 80 },
      { name: "FRQ 1", maxScore: 10 },
      { name: "FRQ 2", maxScore: 10 },
      { name: "FRQ 3", maxScore: 10 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (60% of total score)",
      "80 questions, 90 minutes",
      "Section II: Free Response (40% of total score)",
      "3 questions, 70 minutes",
      "Covers ecosystems, biodiversity, populations, earth systems, and sustainability",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Connect Science to Society", description: "Environmental Science is interdisciplinary. Understand how scientific concepts connect to policy, economics, and ethics." },
      { title: "Practice Math Skills", description: "The exam includes calculations for population growth, energy efficiency, and statistical analysis. Practice dimensional analysis and percent change." },
      { title: "Know Environmental Legislation", description: "Major environmental laws (Clean Air Act, Endangered Species Act, etc.) and international agreements appear on the exam." },
      { title: "Think Systems", description: "Environmental problems are interconnected. Practice tracing how changes in one system affect others (e.g., climate change → ocean acidification → coral bleaching)." },
    ],
    faq: [
      { question: "Is APES mostly memorization?", answer: "There's vocabulary to learn, but the exam emphasizes applying concepts to real-world situations and analyzing environmental problems from multiple perspectives." },
      { question: "Do I need to know specific case studies?", answer: "Yes. The exam uses specific examples (Love Canal, Three Gorges Dam, Aral Sea) to test your understanding of environmental concepts." },
      { question: "How much biology/chemistry is needed?", answer: "Basic biology and chemistry knowledge helps, but the course teaches necessary concepts. Strong reading comprehension and data analysis skills are most important." },
    ],
    relatedSubjects: ["ap-biology", "ap-chemistry", "ap-human-geography", "ap-statistics"],
  },

  "ap-statistics": {
    slug: "ap-statistics",
    name: "AP Statistics",
    maxScore: 100,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 40 },
      { name: "FRQ 1", maxScore: 4 },
      { name: "FRQ 2", maxScore: 4 },
      { name: "FRQ 3", maxScore: 4 },
      { name: "FRQ 4", maxScore: 4 },
      { name: "FRQ 5", maxScore: 4 },
      { name: "FRQ 6", maxScore: 4 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "40 questions, 90 minutes",
      "Section II: Free Response (50% of total score)",
      "6 questions, 90 minutes",
      "Covers data analysis, experimental design, probability, and statistical inference",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Know Your Calculator", description: "A graphing calculator with statistical functions is essential. Practice computing confidence intervals, hypothesis tests, and regression lines quickly." },
      { title: "Understand Experimental Design", description: "Randomization, control groups, and blinding are frequently tested. Know how to identify and explain why each element matters." },
      { title: "Practice Inference Procedures", description: "Confidence intervals and hypothesis tests for means, proportions, and slopes appear on every exam. Know the conditions, formulas, and interpretations." },
      { title: "Interpret in Context", description: "Always interpret statistical results in the context of the problem. Generic answers earn partial credit at best." },
    ],
    faq: [
      { question: "How much math is required?", answer: "Algebra is sufficient. You don't need calculus. The math involves formulas, but the emphasis is on choosing the right procedure and interpreting results." },
      { question: "Is Statistics easier than Calculus?", answer: "Many students find Statistics more approachable because it's conceptual rather than computationally intensive. However, the FRQs require careful, complete explanations." },
      { question: "Do I need to memorize formulas?", answer: "The exam provides a formula sheet, but you must know when and how to apply each formula. Understanding the concepts behind the formulas is more important than memorization." },
    ],
    relatedSubjects: ["ap-calculus-ab", "ap-calculus-bc", "ap-psychology", "ap-computer-science-a"],
  },

  "ap-us-history": {
    slug: "ap-us-history",
    name: "AP US History",
    maxScore: 130,
    mcqWeight: 40,
    frqWeight: 60,
    sections: [
      { name: "MCQ Part A (Stimulus-Based)", maxScore: 28, description: "28 questions, 55 minutes" },
      { name: "MCQ Part B (No Stimulus)", maxScore: 27, description: "27 questions, 20 minutes" },
      { name: "SAQ 1", maxScore: 3 },
      { name: "SAQ 2", maxScore: 3 },
      { name: "SAQ 3", maxScore: 3 },
      { name: "SAQ 4", maxScore: 3 },
      { name: "DBQ", maxScore: 7 },
      { name: "LEQ 1", maxScore: 6 },
      { name: "LEQ 2", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (40% of total score)",
      "Part A: 28 stimulus-based questions, 55 minutes",
      "Part B: 27 non-stimulus questions, 20 minutes",
      "Section II: Short Answer (20% of total score)",
      "4 questions, 3 points each, 40 minutes",
      "Section III: Free Response (40% of total score)",
      "DBQ (7 points): 60 minutes, analyze documents and construct argument",
      "LEQ (6 points each): choose 1 of 2, 40 minutes",
      "Composite score out of 130",
    ],
    tips: [
      { title: "Master the DBQ Rubric", description: "The Document-Based Question is worth 25% of your score. Practice using all 7 documents, providing context, and connecting to broader historical themes." },
      { title: "Know Your Periods", description: "The exam covers 9 chronological periods from 1491 to present. Know the key themes, turning points, and continuities for each period." },
      { title: "Practice SAQ Speed", description: "Short Answer Questions are only 10 minutes each. Practice writing concise, specific answers that directly address all parts of the prompt." },
      { title: "Use HIPPO for Documents", description: "For each document, analyze Historical Context, Intended Audience, Purpose, Point of View, and Outside Information. This ensures full rubric points." },
    ],
    faq: [
      { question: "How important is the DBQ?", answer: "Very important. The DBQ alone is worth 25% of your total score. A strong DBQ (5-7 points) can compensate for weaker multiple choice performance." },
      { question: "Do I need to memorize specific dates?", answer: "Not exact dates, but you need to know the sequence of events and their approximate time periods. The exam tests historical reasoning, not trivia." },
      { question: "What's the hardest period on the exam?", answer: "Periods 3 (1754-1800) and 4 (1800-1848) are often challenging because they involve complex political and economic transformations. Focus on cause-and-effect relationships." },
    ],
    relatedSubjects: ["ap-world-history", "ap-european-history", "ap-us-government", "ap-comparative-government"],
  },

  "ap-world-history": {
    slug: "ap-world-history",
    name: "AP World History",
    maxScore: 120,
    mcqWeight: 40,
    frqWeight: 60,
    sections: [
      { name: "MCQ", maxScore: 55 },
      { name: "SAQ 1", maxScore: 3 },
      { name: "SAQ 2", maxScore: 3 },
      { name: "SAQ 3", maxScore: 3 },
      { name: "DBQ", maxScore: 7 },
      { name: "LEQ", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (40% of total score)",
      "55 questions, 55 minutes",
      "Section II: Short Answer (20% of total score)",
      "3 questions, 40 minutes",
      "Section III: Free Response (40% of total score)",
      "DBQ (7 points): 60 minutes",
      "LEQ (6 points): 40 minutes",
      "Covers global history from 1200 CE to present",
      "Composite score out of 120",
    ],
    tips: [
      { title: "Think Thematically", description: "World History emphasizes themes (trade, religion, technology, empires) across regions and time periods. Practice making connections between civilizations." },
      { title: "Master the DBQ", description: "Like APUSH, the DBQ is critical. Practice analyzing documents from different cultures and time periods, and connecting them to broader global processes." },
      { title: "Know Key Comparisons", description: "The exam frequently asks you to compare civilizations (e.g., Chinese and Islamic empires, Mongol and Roman expansion). Prepare comparative frameworks." },
      { title: "Practice Cause and Effect", description: "Historical reasoning is central to World History. Practice explaining why events happened and what consequences followed, both short-term and long-term." },
    ],
    faq: [
      { question: "Is World History harder than US History?", answer: "Many students find World History more manageable because the scope is broader and less detail-oriented than US History. However, the global perspective requires strong comparative thinking." },
      { question: "Do I need to know every civilization?", answer: "No, but you need to know major civilizations in each region (East Asia, South Asia, Middle East, Europe, Americas, Africa) and how they interacted through trade, conflict, and cultural exchange." },
      { question: "How important is the 1200 start date?", answer: "Very. The modern course starts in 1200 CE, focusing on the rise of global networks. Earlier civilizations are covered only as background for understanding later developments." },
    ],
    relatedSubjects: ["ap-us-history", "ap-european-history", "ap-human-geography", "ap-comparative-government"],
  },

  "ap-european-history": {
    slug: "ap-european-history",
    name: "AP European History",
    maxScore: 120,
    mcqWeight: 40,
    frqWeight: 60,
    sections: [
      { name: "MCQ", maxScore: 55 },
      { name: "SAQ 1", maxScore: 3 },
      { name: "SAQ 2", maxScore: 3 },
      { name: "SAQ 3", maxScore: 3 },
      { name: "DBQ", maxScore: 7 },
      { name: "LEQ", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (40% of total score)",
      "55 questions, 55 minutes",
      "Section II: Short Answer (20% of total score)",
      "3 questions, 40 minutes",
      "Section III: Free Response (40% of total score)",
      "DBQ (7 points): 60 minutes",
      "LEQ (6 points): 40 minutes",
      "Covers European history from 1450 to present",
      "Composite score out of 120",
    ],
    tips: [
      { title: "Master the Themes", description: "European History emphasizes interaction between Europe and the world, poverty and prosperity, objective knowledge and subjective visions, and states and other institutions of power." },
      { title: "Know Art and Culture", description: "The exam frequently tests knowledge of Renaissance art, Enlightenment philosophy, and 20th-century cultural movements. Connect artistic developments to broader historical trends." },
      { title: "Practice Document Analysis", description: "Euro DBQs often include artistic, philosophical, or political documents. Practice analyzing bias, purpose, and audience for diverse document types." },
      { title: "Connect to Global Context", description: "The course emphasizes Europe's relationship with the world. Practice explaining how European actions affected other regions and vice versa." },
    ],
    faq: [
      { question: "How is Euro History different from World History?", answer: "Euro History focuses exclusively on European developments with deeper detail. World History covers all regions with broader, comparative themes." },
      { question: "Is the Renaissance heavily tested?", answer: "Yes, the Renaissance and Reformation are foundational topics. Know key figures, artistic innovations, and religious reform movements in detail." },
      { question: "How important is the World Wars content?", answer: "Very. 20th-century Europe, including both World Wars, the Cold War, and European integration, constitutes a significant portion of the exam." },
    ],
    relatedSubjects: ["ap-world-history", "ap-us-history", "ap-art-history", "ap-comparative-government"],
  },

  "ap-us-government": {
    slug: "ap-us-government",
    name: "AP US Government",
    maxScore: 120,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 55 },
      { name: "FRQ 1 (Concept Application)", maxScore: 3 },
      { name: "FRQ 2 (SCOTUS Comparison)", maxScore: 4 },
      { name: "FRQ 3 (Argument Essay)", maxScore: 6 },
      { name: "FRQ 4 (Quantitative Analysis)", maxScore: 4 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "55 questions, 80 minutes",
      "Section II: Free Response (50% of total score)",
      "4 questions, 100 minutes",
      "Covers the US political system, Constitution, institutions, and public policy",
      "Composite score out of 120",
    ],
    tips: [
      { title: "Know the Constitution", description: "The Constitution, Bill of Rights, and key amendments are foundational. Know specific articles, clauses, and how they've been interpreted over time." },
      { title: "Master Required Documents", description: "The exam requires knowledge of 15 foundational documents and 15 Supreme Court cases. Know the facts, holding, and significance of each." },
      { title: "Connect to Current Events", description: "Government is constantly evolving. Connect constitutional principles to current political debates and recent Supreme Court decisions." },
      { title: "Practice the Argument Essay", description: "The Argument Essay requires you to develop a thesis using required documents and your own knowledge. Practice constructing clear, evidence-based arguments." },
    ],
    faq: [
      { question: "How many Supreme Court cases do I need to know?", answer: "15 required cases. Know the constitutional issue, facts, holding, reasoning, and significance of each. Additional cases may appear as stimulus material." },
      { question: "Is current events knowledge required?", answer: "Not explicitly, but connecting constitutional principles to current events strengthens your essays and demonstrates deeper understanding." },
      { question: "What's the hardest part of the exam?", answer: "Many students struggle with the SCOTUS comparison FRQ, which requires comparing two cases on similar constitutional issues. Practice identifying constitutional principles across multiple cases." },
    ],
    relatedSubjects: ["ap-comparative-government", "ap-us-history", "ap-psychology", "ap-macroeconomics"],
  },

  "ap-comparative-government": {
    slug: "ap-comparative-government",
    name: "AP Comparative Government",
    maxScore: 120,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 55 },
      { name: "FRQ 1 (Conceptual)", maxScore: 3 },
      { name: "FRQ 2 (Country Comparison)", maxScore: 3 },
      { name: "FRQ 3 (Quantitative)", maxScore: 3 },
      { name: "FRQ 4 (Argument)", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "55 questions, 80 minutes",
      "Section II: Free Response (50% of total score)",
      "4 questions, 90 minutes",
      "Compares political systems across UK, Russia, China, Iran, Mexico, and Nigeria",
      "Composite score out of 120",
    ],
    tips: [
      { title: "Create Comparison Charts", description: "Organize information about the 6 countries in charts comparing regime type, executive structure, legislative structure, judicial independence, and political participation." },
      { title: "Know Country-Specific Details", description: "Each country has unique political challenges and reforms. Know recent events (within 5 years) for each country, especially leadership changes and constitutional reforms." },
      { title: "Understand Democratization", description: "The concept of democratization and its challenges is central. Practice explaining why some countries democratize while others remain authoritarian." },
      { title: "Use Specific Evidence", description: "Vague comparisons earn partial credit. Always cite specific policies, events, or institutions when comparing countries." },
    ],
    faq: [
      { question: "Do I need to know all 6 countries equally?", answer: "Yes, all 6 countries (UK, Russia, China, Iran, Mexico, Nigeria) are tested equally. Know the political institutions, challenges, and recent developments for each." },
      { question: "Is this easier than US Government?", answer: "Many students find Comparative more interesting because of the global perspective, but it requires memorizing details about 6 different political systems rather than one." },
      { question: "How current should my knowledge be?", answer: "Know major events within the last 5 years. The exam occasionally includes questions about recent elections, leadership changes, or policy reforms." },
    ],
    relatedSubjects: ["ap-us-government", "ap-human-geography", "ap-world-history", "ap-macroeconomics"],
  },

  "ap-english-language": {
    slug: "ap-english-language",
    name: "AP English Language",
    maxScore: 100,
    mcqWeight: 45,
    frqWeight: 55,
    sections: [
      { name: "MCQ Part A (Reading)", maxScore: 23, description: "23 questions, 45 minutes" },
      { name: "MCQ Part B (Writing)", maxScore: 22, description: "22 questions, 45 minutes" },
      { name: "Synthesis Essay", maxScore: 6 },
      { name: "Rhetorical Analysis Essay", maxScore: 6 },
      { name: "Argument Essay", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (45% of total score)",
      "Part A: 23 reading questions, 45 minutes",
      "Part B: 22 writing questions, 45 minutes",
      "Tests rhetorical analysis, argument, and synthesis skills",
      "Section II: Free Response (55% of total score)",
      "Synthesis Essay (6 points): 15 minutes reading + 40 minutes writing",
      "Rhetorical Analysis Essay (6 points): 40 minutes",
      "Argument Essay (6 points): 40 minutes",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Master the Rhetorical Triangle", description: "Every essay and MCQ involves ethos, pathos, and logos. Practice identifying how authors use these appeals and explaining their effect on the audience." },
      { title: "Practice Timed Writing", description: "You have 40 minutes per essay. Practice writing complete, well-organized essays within the time limit. Outline for 5 minutes, write for 30, revise for 5." },
      { title: "Build Your Evidence Bank", description: "For the argument essay, prepare a mental bank of examples from history, literature, current events, and personal experience. Specific, relevant evidence strengthens your claim." },
      { title: "Analyze, Don't Summarize", description: "The rhetorical analysis essay requires analyzing HOW an author achieves their purpose, not summarizing WHAT they say. Focus on specific rhetorical choices and their effects." },
    ],
    faq: [
      { question: "How is the synthesis essay different from the argument essay?", answer: "The synthesis essay requires you to use at least 3 of 6-7 provided sources to support your position. The argument essay uses your own knowledge and experience without provided sources." },
      { question: "Do spelling and grammar matter?", answer: "They matter, but content and analysis matter more. A few minor errors won't significantly hurt your score if your argument is strong and well-supported. However, pervasive errors that obscure meaning will lower your score." },
      { question: "How can I improve my MCQ speed?", answer: "Practice reading passages actively — annotate the author's purpose, tone, and main argument as you read. For grammar questions, learn the 20 most commonly tested rules (comma splices, subject-verb agreement, pronoun reference, etc.)." },
    ],
    relatedSubjects: ["ap-english-literature", "ap-psychology", "ap-us-history", "ap-seminar"],
  },

  "ap-english-literature": {
    slug: "ap-english-literature",
    name: "AP English Literature",
    maxScore: 100,
    mcqWeight: 45,
    frqWeight: 55,
    sections: [
      { name: "MCQ", maxScore: 55 },
      { name: "FRQ 1 (Poetry Analysis)", maxScore: 6 },
      { name: "FRQ 2 (Prose Analysis)", maxScore: 6 },
      { name: "FRQ 3 (Literary Argument)", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (45% of total score)",
      "55 questions, 60 minutes",
      "Section II: Free Response (55% of total score)",
      "Poetry Analysis (6 points): 40 minutes",
      "Prose Analysis (6 points): 40 minutes",
      "Literary Argument (6 points): 40 minutes",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Read Widely", description: "The exam tests your ability to analyze unfamiliar texts. Reading diverse poetry, prose, and drama throughout the year builds analytical skills." },
      { title: "Master Literary Devices", description: "Know how to identify and analyze imagery, symbolism, diction, syntax, tone, and figurative language. Don't just list devices — explain their effect." },
      { title: "Practice Close Reading", description: "The poetry and prose essays require careful, line-by-line analysis. Practice annotating texts for meaning, structure, and literary techniques." },
      { title: "Prepare Literary Examples", description: "For the literary argument essay, prepare examples from novels, plays, and poems you've studied. Know characters, themes, and key scenes in detail." },
    ],
    faq: [
      { question: "Do I need to memorize specific poems?", answer: "No, the exam provides the poems and prose passages. However, familiarity with common poetic forms and literary movements helps you analyze unfamiliar texts." },
      { question: "Is AP Lit harder than AP Lang?", answer: "Many students find Lit more challenging because it requires deeper literary analysis and familiarity with complex texts. The reading level is generally higher than Lang." },
      { question: "What books should I read?", answer: "Read a mix of classic and contemporary literature across genres. Focus on works with strong character development, thematic depth, and literary technique (e.g., Shakespeare, Austen, Morrison, Faulkner)." },
    ],
    relatedSubjects: ["ap-english-language", "ap-art-history", "ap-psychology", "ap-us-history"],
  },

  "ap-psychology": {
    slug: "ap-psychology",
    name: "AP Psychology",
    maxScore: 114,
    mcqWeight: 67,
    frqWeight: 33,
    sections: [
      { name: "MCQ", maxScore: 100, description: "100 questions, 70 minutes" },
      { name: "FRQ 1 (Concept Application)", maxScore: 7 },
      { name: "FRQ 2 (Research Design)", maxScore: 7 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (66.7% of total score)",
      "100 questions, 70 minutes",
      "Covers all 9 units of the curriculum",
      "No calculator permitted",
      "Section II: Free Response (33.3% of total score)",
      "2 questions, 50 minutes",
      "Question 1: Concept Application (7 points)",
      "Question 2: Research Design (7 points)",
      "Composite score out of 114",
    ],
    tips: [
      { title: "Know the Key Researchers", description: "The exam frequently asks about specific psychologists and their contributions. Create flashcards for the 30 most cited researchers (Pavlov, Skinner, Milgram, Zimbardo, etc.)." },
      { title: "Understand Research Methods", description: "The Research Design FRQ requires you to identify variables, operational definitions, and ethical concerns. Practice designing studies and identifying flaws in existing ones." },
      { title: "Connect Concepts Across Units", description: "Psychology is interconnected. The biological bases of behavior (Unit 2) connect to sensation/perception (Unit 3) and motivation (Unit 7). Look for these cross-unit connections." },
      { title: "Use Real-World Examples", description: "For the Concept Application FRQ, prepare concrete examples from your own life, current events, or pop culture. Specific, accurate examples earn full points." },
    ],
    faq: [
      { question: "Is AP Psychology mostly memorization?", answer: "Yes, but with application. You need to memorize key terms, researchers, and theories. However, the FRQs and many MCQs require you to apply these concepts to scenarios, not just define them." },
      { question: "How hard is it to get a 5?", answer: "Historically, about 15-18% of students score a 5. Psychology is considered one of the more accessible AP exams, but the large volume of content requires consistent review throughout the year." },
      { question: "Do I need to know statistics?", answer: "Basic statistics only. You need to understand mean, median, mode, standard deviation, correlation coefficients, and statistical significance. No advanced calculations are required." },
    ],
    relatedSubjects: ["ap-human-geography", "ap-us-history", "ap-biology", "ap-statistics"],
  },

  "ap-human-geography": {
    slug: "ap-human-geography",
    name: "AP Human Geography",
    maxScore: 120,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 60 },
      { name: "FRQ 1", maxScore: 7 },
      { name: "FRQ 2", maxScore: 7 },
      { name: "FRQ 3", maxScore: 7 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "60 questions, 60 minutes",
      "Section II: Free Response (50% of total score)",
      "3 questions, 75 minutes",
      "Covers population, migration, culture, language, religion, and urban geography",
      "Composite score out of 120",
    ],
    tips: [
      { title: "Know Your Models", description: "Human Geography is model-heavy. Know the demographic transition model, Ravenstein's laws, von Thünen model, and others. Understand their assumptions and limitations." },
      { title: "Use Real-World Examples", description: "The exam rewards specific, contemporary examples. Know current events related to migration, urbanization, and cultural conflicts around the world." },
      { title: "Practice Map Analysis", description: "Many questions include maps showing population density, migration patterns, or economic development. Practice interpreting spatial data and drawing conclusions." },
      { title: "Connect to Current Trends", description: "Urbanization, globalization, and sustainability are major themes. Practice explaining how these forces affect different regions differently." },
    ],
    faq: [
      { question: "Is Human Geography mostly memorization?", answer: "There's vocabulary to learn, but the emphasis is on applying geographic concepts to real-world situations. The FRQs require analysis, not just definitions." },
      { question: "Do I need to know world capitals?", answer: "No, but you should know major world regions and their characteristics. The exam tests concepts, not place-name memorization." },
      { question: "How important are the models?", answer: "Very. Models are central to Human Geography. Know the major models, their stages/assumptions, and be able to critique them using real-world examples." },
    ],
    relatedSubjects: ["ap-psychology", "ap-us-history", "ap-world-history", "ap-environmental-science"],
  },

  "ap-macroeconomics": {
    slug: "ap-macroeconomics",
    name: "AP Macroeconomics",
    maxScore: 100,
    mcqWeight: 66,
    frqWeight: 33,
    sections: [
      { name: "MCQ", maxScore: 60 },
      { name: "FRQ 1 (Long)", maxScore: 10 },
      { name: "FRQ 2 (Short)", maxScore: 5 },
      { name: "FRQ 3 (Short)", maxScore: 5 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (66.7% of total score)",
      "60 questions, 70 minutes",
      "Section II: Free Response (33.3% of total score)",
      "1 long question (10 points), 2 short questions (5 points each)",
      "Covers national income, price determination, economic performance, and international economics",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Master Graphs", description: "Macroeconomics is graph-heavy. Practice drawing and shifting AD/AS, Phillips Curve, money market, and loanable funds graphs quickly and accurately." },
      { title: "Know the Formulas", description: "GDP, inflation rate, unemployment rate, money multiplier, and spending multiplier formulas appear frequently. Practice calculating these under time pressure." },
      { title: "Understand Policy Trade-offs", description: "Fiscal and monetary policy have short-run and long-run effects. Practice explaining the trade-offs between inflation and unemployment, and between growth and stability." },
      { title: "Connect to Current Events", description: "The exam often uses current or recent economic conditions as context. Follow economic news and practice applying macro concepts to real situations." },
    ],
    faq: [
      { question: "How much math is required?", answer: "Basic algebra and arithmetic. You'll calculate percentages, ratios, and use formulas. No calculus is needed." },
      { question: "Should I take Micro before Macro?", answer: "Either order works. Micro focuses on individual markets, Macro on the entire economy. Some students find Micro more intuitive, others prefer Macro's big-picture approach." },
      { question: "How important is the FRQ?", answer: "The FRQ is 33% of your score and tests deeper understanding. Practice explaining economic concepts verbally, not just graphing them." },
    ],
    relatedSubjects: ["ap-microeconomics", "ap-us-government", "ap-calculus-ab", "ap-statistics"],
  },

  "ap-microeconomics": {
    slug: "ap-microeconomics",
    name: "AP Microeconomics",
    maxScore: 90,
    mcqWeight: 66,
    frqWeight: 33,
    sections: [
      { name: "MCQ", maxScore: 60 },
      { name: "FRQ 1 (Long)", maxScore: 10 },
      { name: "FRQ 2 (Short)", maxScore: 5 },
      { name: "FRQ 3 (Short)", maxScore: 5 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (66.7% of total score)",
      "60 questions, 70 minutes",
      "Section II: Free Response (33.3% of total score)",
      "1 long question (10 points), 2 short questions (5 points each)",
      "Covers supply and demand, market structures, factor markets, and market failure",
      "Composite score out of 90",
    ],
    tips: [
      { title: "Master Supply and Demand", description: "This is the foundation of all microeconomics. Practice shifting curves, identifying equilibrium changes, and calculating consumer/producer surplus." },
      { title: "Know Market Structures", description: "Perfect competition, monopoly, oligopoly, and monopolistic competition each have distinct characteristics. Know the graphs, efficiency, and profit maximization for each." },
      { title: "Practice Elasticity Calculations", description: "Price elasticity, income elasticity, and cross-price elasticity appear on every exam. Practice the midpoint formula and interpreting elasticity values." },
      { title: "Understand Externalities", description: "Market failure, including externalities and public goods, is frequently tested. Practice drawing graphs showing deadweight loss and optimal government intervention." },
    ],
    faq: [
      { question: "Is Micro easier than Macro?", answer: "Many students find Micro more intuitive because it deals with concrete examples (firms, consumers) rather than abstract aggregates (GDP, inflation)." },
      { question: "Do I need to draw perfect graphs?", answer: "Graphs don't need to be artistic, but they must be labeled correctly with axes, curves, equilibrium points, and shaded areas. Practice drawing quickly under time pressure." },
      { question: "How important is the math?", answer: "Moderate. You'll calculate elasticities, surpluses, and profit/loss. The math is straightforward algebra, but accuracy under time pressure matters." },
    ],
    relatedSubjects: ["ap-macroeconomics", "ap-calculus-ab", "ap-statistics", "ap-us-government"],
  },

  "ap-computer-science-a": {
    slug: "ap-computer-science-a",
    name: "AP Computer Science A",
    maxScore: 80,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 40 },
      { name: "FRQ 1 (Methods and Control Structures)", maxScore: 9 },
      { name: "FRQ 2 (Classes)", maxScore: 9 },
      { name: "FRQ 3 (Array/ArrayList)", maxScore: 9 },
      { name: "FRQ 4 (2D Array)", maxScore: 9 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "40 questions, 90 minutes",
      "Section II: Free Response (50% of total score)",
      "4 questions, 90 minutes",
      "Covers Java programming, data structures, algorithms, and object-oriented design",
      "Composite score out of 80",
    ],
    tips: [
      { title: "Practice Writing Code by Hand", description: "The FRQs require handwritten Java code. Practice writing clear, correctly formatted code without IDE assistance. Syntax errors cost points." },
      { title: "Master Array and ArrayList Traversal", description: "These appear on every exam. Know how to iterate, search, and modify arrays and ArrayLists using both for loops and enhanced for loops." },
      { title: "Understand Object-Oriented Design", description: "Classes, inheritance, and polymorphism are heavily tested. Practice designing classes with appropriate fields, constructors, and methods." },
      { title: "Trace Code on Paper", description: "Many MCQs require tracing code execution. Practice stepping through loops and recursive methods manually to predict output." },
    ],
    faq: [
      { question: "Do I need prior programming experience?", answer: "No, but it helps. The course is designed for beginners, but students with prior experience (especially in Java) have an advantage in the first few units." },
      { question: "Is the exam on a computer?", answer: "No. Both MCQ and FRQ are paper-based. The FRQs require you to write Java code by hand, so practice handwriting code clearly and legibly." },
      { question: "How important is the GridWorld case study?", answer: "GridWorld is no longer part of the exam (discontinued after 2014). Focus on the Java subset specified in the Course Description." },
    ],
    relatedSubjects: ["ap-computer-science-principles", "ap-calculus-ab", "ap-statistics", "ap-physics-1"],
  },

  "ap-computer-science-principles": {
    slug: "ap-computer-science-principles",
    name: "AP Computer Science Principles",
    maxScore: 100,
    mcqWeight: 70,
    frqWeight: 30,
    sections: [
      { name: "MCQ", maxScore: 70 },
      { name: "Create Performance Task", maxScore: 30 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (70% of total score)",
      "70 questions, 120 minutes",
      "Section II: Create Performance Task (30% of total score)",
      "Submit a program, video, and written responses",
      "Covers computational thinking, programming, data, internet, and global impact",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Start the Create Task Early", description: "The Performance Task is 30% of your score and requires significant time. Start planning and coding your project at least 2 months before the deadline." },
      { title: "Practice Pseudocode", description: "The exam tests your ability to express algorithms in pseudocode. Practice writing clear, step-by-step procedures without worrying about syntax." },
      { title: "Understand the Internet", description: "TCP/IP, DNS, HTTP, and encryption are tested. Know how data travels across networks and how protocols enable communication." },
      { title: "Think About Impact", description: "The 'global impact' unit requires you to analyze the benefits and risks of computing innovations. Practice identifying stakeholders and unintended consequences." },
    ],
    faq: [
      { question: "Do I need to know a specific programming language?", answer: "No. The exam is language-agnostic for the MCQ. For the Create Task, you can use any language (Python, JavaScript, Scratch, etc.)." },
      { question: "How is the Create Task scored?", answer: "Your program is evaluated on functionality, design, and complexity. Your written responses explain your development process and algorithm analysis." },
      { question: "Is CSP easier than CSA?", answer: "Many students find CSP more accessible because it focuses on concepts rather than coding syntax. However, the broad scope (from binary to internet to ethics) requires diverse knowledge." },
    ],
    relatedSubjects: ["ap-computer-science-a", "ap-statistics", "ap-psychology", "ap-macroeconomics"],
  },

  "ap-art-history": {
    slug: "ap-art-history",
    name: "AP Art History",
    maxScore: 200,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 80 },
      { name: "FRQ 1 (Comparison)", maxScore: 8 },
      { name: "FRQ 2 (Visual/Contextual Analysis)", maxScore: 6 },
      { name: "FRQ 3 (Visual/Contextual Analysis)", maxScore: 6 },
      { name: "FRQ 4 (Attribution)", maxScore: 6 },
      { name: "FRQ 5 (Continuity/Change)", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "80 questions, 60 minutes",
      "Section II: Free Response (50% of total score)",
      "5 questions, 120 minutes",
      "Covers art from prehistoric times to present across global cultures",
      "Composite score out of 200",
    ],
    tips: [
      { title: "Know the 250 Works", description: "The exam tests 250 required works of art. Know the title, artist, date, medium, and cultural context for each. Flashcards are essential." },
      { title: "Practice Visual Analysis", description: "Many questions show an image and ask for analysis. Practice describing formal qualities (composition, color, technique) and connecting them to meaning." },
      { title: "Understand Cultural Context", description: "Art doesn't exist in a vacuum. Know how political, religious, and social contexts influenced artistic production in each culture and time period." },
      { title: "Compare and Contrast", description: "The comparison essay requires analyzing two works from different cultures or periods. Practice identifying similarities in function despite differences in form." },
    ],
    faq: [
      { question: "Do I need to be an artist?", answer: "No artistic skill is required. The exam tests your ability to analyze and contextualize art, not create it." },
      { question: "How many works do I need to memorize?", answer: "250 required works. Know identifying information (artist, title, date, culture) and be able to analyze form, function, content, and context." },
      { question: "Is the course mostly Western art?", answer: "No, it's truly global. The 250 works span prehistoric Europe, ancient Mediterranean, early Americas, Africa, Asia, Near East, and global contemporary art." },
    ],
    relatedSubjects: ["ap-english-literature", "ap-world-history", "ap-european-history", "ap-music-theory"],
  },

  "ap-music-theory": {
    slug: "ap-music-theory",
    name: "AP Music Theory",
    maxScore: 100,
    mcqWeight: 45,
    frqWeight: 55,
    sections: [
      { name: "MCQ", maxScore: 75 },
      { name: "FRQ 1 (Melodic Dictation)", maxScore: 9 },
      { name: "FRQ 2 (Harmonic Dictation)", maxScore: 9 },
      { name: "FRQ 3 (Part Writing from Figured Bass)", maxScore: 9 },
      { name: "FRQ 4 (Part Writing from Roman Numerals)", maxScore: 9 },
      { name: "FRQ 5 (Composition)", maxScore: 9 },
      { name: "FRQ 6 (Sight Singing)", maxScore: 9 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (45% of total score)",
      "75 questions, 约 80 minutes",
      "Section II: Free Response (55% of total score)",
      "Includes melodic/harmonic dictation, part writing, composition, and sight singing",
      "Covers music fundamentals, harmony, composition, and aural skills",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Develop Your Ear", description: "Aural skills (dictation and sight singing) are crucial. Practice identifying intervals, chords, and progressions by ear daily using ear training apps." },
      { title: "Master Part Writing Rules", description: "Voice leading rules (no parallel fifths/octaves, proper resolution of tendency tones) are strictly tested. Practice four-part harmony until rules become automatic." },
      { title: "Know Your Scales and Modes", description: "Major, natural minor, harmonic minor, melodic minor, and modes appear frequently. Practice identifying and writing scales in all keys." },
      { title: "Practice Sight Singing", description: "The sight singing exam requires you to sing an unfamiliar melody accurately. Practice solfège daily and record yourself to check pitch accuracy." },
    ],
    faq: [
      { question: "Do I need to play an instrument?", answer: "Piano skills are highly recommended because the exam requires reading bass and treble clef, and keyboard familiarity helps with harmony and part writing." },
      { question: "Is AP Music Theory mostly listening?", answer: "About 55% of the score comes from aural tasks (dictation, sight singing). Strong ear training is essential for success." },
      { question: "How important is composition?", answer: "The composition FRQ requires writing a bass line and harmonizing a melody. Practice composing simple phrases that follow harmonic conventions." },
    ],
    relatedSubjects: ["ap-art-history", "ap-english-literature", "ap-psychology", "ap-studio-art"],
  },

  "ap-studio-art": {
    slug: "ap-studio-art",
    name: "AP Studio Art",
    maxScore: 100,
    mcqWeight: 0,
    frqWeight: 100,
    sections: [
      { name: "Selected Works (Sustained Investigation)", maxScore: 60 },
      { name: "Selected Works (Quality)", maxScore: 40 },
    ],
    scoringExplanation: [
      "AP Studio Art is portfolio-based — no exam",
      "Sustained Investigation (60% of score)",
      "15 digital images showing in-depth exploration of a theme",
      "Written commentary explaining inquiry and process",
      "Selected Works (40% of score)",
      "5 physical works demonstrating quality",
      "Digital images of these works submitted",
      "Scored on 1-5 scale by portfolio review",
    ],
    tips: [
      { title: "Choose a Meaningful Theme", description: "Your Sustained Investigation needs a coherent, personally meaningful theme. Avoid generic topics; choose something you can explore deeply over many works." },
      { title: "Show Process and Growth", description: "Include sketches, experiments, and revisions in your portfolio. The examiners want to see how your ideas developed, not just final products." },
      { title: "Document Everything Well", description: "Photograph your work professionally with good lighting and neutral backgrounds. Poor documentation can make excellent work look mediocre." },
      { title: "Write Thoughtful Commentary", description: "Your written statements should articulate your inquiry, show evidence of research, and explain artistic decisions. Specificity and depth earn high scores." },
    ],
    faq: [
      { question: "Do I need to take an exam?", answer: "No. Studio Art is assessed entirely through portfolio submission. There is no multiple choice or free response exam." },
      { question: "What are the three portfolio types?", answer: "2-D Art and Design, 3-D Art and Design, and Drawing. Each has different requirements but the same scoring rubric." },
      { question: "How important is the written commentary?", answer: "Very. Your commentary explains your artistic inquiry and process. Strong writing that demonstrates deep thinking can significantly improve your score." },
    ],
    relatedSubjects: ["ap-art-history", "ap-music-theory", "ap-english-literature", "ap-psychology"],
  },

  "ap-spanish-language": {
    slug: "ap-spanish-language",
    name: "AP Spanish Language",
    maxScore: 100,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ Part A (Reading)", maxScore: 30 },
      { name: "MCQ Part B (Listening)", maxScore: 34 },
      { name: "FRQ 1 (Email Reply)", maxScore: 6 },
      { name: "FRQ 2 (Argument Essay)", maxScore: 6 },
      { name: "FRQ 3 (Conversation)", maxScore: 6 },
      { name: "FRQ 4 (Cultural Comparison)", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "Part A: Reading comprehension, 30 questions",
      "Part B: Listening comprehension, 34 questions",
      "Section II: Free Response (50% of total score)",
      "Email reply, persuasive essay, simulated conversation, cultural comparison",
      "Tests interpersonal, interpretive, and presentational communication",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Immerse Yourself Daily", description: "Listen to Spanish podcasts, watch Spanish shows with subtitles, and read Spanish news. Daily exposure is more effective than cramming." },
      { title: "Practice the Conversational Format", description: "The simulated conversation requires quick, natural responses. Practice with a partner or recording device, responding to prompts within 20 seconds." },
      { title: "Build Cultural Knowledge", description: "The cultural comparison requires discussing practices in Spanish-speaking communities. Research customs, celebrations, and social norms across the Spanish-speaking world." },
      { title: "Time Your Writing", description: "You have limited time for each writing task. Practice writing complete, well-organized responses within the time limits using transition words and varied vocabulary." },
    ],
    faq: [
      { question: "How fluent do I need to be?", answer: "Intermediate-high to advanced proficiency. You should be comfortable expressing complex ideas, using varied vocabulary, and understanding native speakers at normal speed." },
      { question: "Is the exam entirely in Spanish?", answer: "Yes, except for instructions. All reading, listening, speaking, and writing tasks use Spanish exclusively." },
      { question: "How is the speaking section scored?", answer: "Your spoken responses are recorded and scored on delivery, language use, and topic development. Fluency, accuracy, and cultural appropriateness all matter." },
    ],
    relatedSubjects: ["ap-spanish-literature", "ap-french-language", "ap-latin", "ap-italian-language"],
  },

  "ap-spanish-literature": {
    slug: "ap-spanish-literature",
    name: "AP Spanish Literature",
    maxScore: 100,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ", maxScore: 65 },
      { name: "FRQ 1 (Text Explanation)", maxScore: 6 },
      { name: "FRQ 2 (Text and Art Comparison)", maxScore: 6 },
      { name: "FRQ 3 (Analysis of Single Text)", maxScore: 6 },
      { name: "FRQ 4 (Argument Essay)", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "65 questions, 80 minutes",
      "Section II: Free Response (50% of total score)",
      "4 essays analyzing literary texts",
      "Covers Spanish, Latin American, and US Hispanic literature",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Read the Required Texts", description: "The exam tests 38 required works. Read each text carefully, noting themes, literary devices, and historical context. Annotate as you read." },
      { title: "Master Literary Terminology", description: "Know Spanish literary terms (metáfora, símbolo, ironía, etc.) and be able to identify and analyze devices in context, not just list them." },
      { title: "Practice Timed Essays", description: "You have limited time for each essay. Practice planning and writing complete literary analyses within the time constraints." },
      { title: "Connect to Historical Context", description: "Literature reflects its time. Know the historical and cultural context of each work and how it influenced the author's choices." },
    ],
    faq: [
      { question: "Do I need to read all 38 texts?", answer: "Yes, the exam tests knowledge of all required works. However, you can read excerpts for some longer works, but know the complete plot and major themes." },
      { question: "Is this harder than Spanish Language?", answer: "Many students find Literature more challenging because it requires deep literary analysis in Spanish, not just communication skills. Strong reading and writing skills are essential." },
      { question: "How important is cultural context?", answer: "Very. The exam asks how historical, social, and cultural contexts shape literary works. Know the major historical periods of Spanish and Latin American literature." },
    ],
    relatedSubjects: ["ap-spanish-language", "ap-french-language", "ap-english-literature", "ap-latin"],
  },

  "ap-french-language": {
    slug: "ap-french-language",
    name: "AP French Language",
    maxScore: 100,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ Part A (Reading)", maxScore: 30 },
      { name: "MCQ Part B (Listening)", maxScore: 35 },
      { name: "FRQ 1 (Email Reply)", maxScore: 6 },
      { name: "FRQ 2 (Argument Essay)", maxScore: 6 },
      { name: "FRQ 3 (Conversation)", maxScore: 6 },
      { name: "FRQ 4 (Cultural Comparison)", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "Part A: Reading comprehension, 30 questions",
      "Part B: Listening comprehension, 35 questions",
      "Section II: Free Response (50% of total score)",
      "Email reply, persuasive essay, simulated conversation, cultural comparison",
      "Tests interpersonal, interpretive, and presentational communication",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Immerse in French Media", description: "Watch French films, listen to French podcasts, and read French news (Le Monde, France 24). Exposure to authentic language improves comprehension and vocabulary." },
      { title: "Master French Pronunciation", description: "The speaking section requires clear pronunciation. Practice liaisons, nasal vowels, and the French 'r'. Record yourself and compare to native speakers." },
      { title: "Build Francophone Cultural Knowledge", description: "Know customs, history, and current events in France, Quebec, and Francophone Africa. The cultural comparison requires discussing practices across regions." },
      { title: "Practice Formal Register", description: "French has distinct formal and informal registers. The exam often requires formal language (vous, conditional, subjunctive) in writing and speaking tasks." },
    ],
    faq: [
      { question: "How fluent should I be?", answer: "Intermediate-high proficiency. You should understand native speakers, read authentic texts, and express complex ideas with some accuracy." },
      { question: "Is French harder than Spanish?", answer: "French pronunciation and grammar (gender agreement, subjunctive) are often considered more challenging. However, both exams follow the same format and scoring." },
      { question: "Do I need to know French literature?", answer: "Not for the Language exam. The Language exam tests communication skills. Literature is only tested in the separate AP French Literature and Culture exam." },
    ],
    relatedSubjects: ["ap-spanish-language", "ap-german-language", "ap-italian-language", "ap-latin"],
  },

  "ap-german-language": {
    slug: "ap-german-language",
    name: "AP German Language",
    maxScore: 100,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ Part A (Reading)", maxScore: 30 },
      { name: "MCQ Part B (Listening)", maxScore: 35 },
      { name: "FRQ 1 (Email Reply)", maxScore: 6 },
      { name: "FRQ 2 (Argument Essay)", maxScore: 6 },
      { name: "FRQ 3 (Conversation)", maxScore: 6 },
      { name: "FRQ 4 (Cultural Comparison)", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "Part A: Reading comprehension, 30 questions",
      "Part B: Listening comprehension, 35 questions",
      "Section II: Free Response (50% of total score)",
      "Email reply, persuasive essay, simulated conversation, cultural comparison",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Master Case System", description: "German's four cases (nominative, accusative, dative, genitive) are essential. Practice identifying case requirements for verbs, prepositions, and adjective endings." },
      { title: "Build Compound Word Vocabulary", description: "German creates long compound words. Learn common roots and how to decompose compounds to understand meaning from context." },
      { title: "Practice Word Order", description: "German word order rules (verb second, verb final in subordinate clauses) are strict. Practice constructing sentences with correct word order in all clause types." },
      { title: "Know German-Speaking Cultures", description: "Germany, Austria, and Switzerland have distinct cultures. Know differences in customs, education, and current events across German-speaking regions." },
    ],
    faq: [
      { question: "Is German harder than Romance languages?", answer: "Many students find German grammar (cases, gender, word order) more complex than Spanish or French. However, German pronunciation is more phonetic than French." },
      { question: "How important is vocabulary?", answer: "Very. German has precise vocabulary for technical and academic concepts. Build vocabulary through reading authentic texts and using spaced repetition." },
      { question: "Do I need to know Swiss German?", answer: "No. The exam tests Standard German (Hochdeutsch). However, you should be aware that Swiss German and Austrian German have some vocabulary differences." },
    ],
    relatedSubjects: ["ap-french-language", "ap-spanish-language", "ap-latin", "ap-italian-language"],
  },

  "ap-latin": {
    slug: "ap-latin",
    name: "AP Latin",
    maxScore: 100,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ (Reading Comprehension)", maxScore: 50 },
      { name: "FRQ 1 (Translation)", maxScore: 15 },
      { name: "FRQ 2 (Short Answer)", maxScore: 15 },
      { name: "FRQ 3 (Essay)", maxScore: 20 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "50 questions testing reading comprehension of Latin passages",
      "Section II: Free Response (50% of total score)",
      "Translation, short answer analysis, and essay",
      "Covers Latin language and Roman culture through reading classical texts",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Read Extensively", description: "Read beyond the required syllabus. Exposure to diverse Latin texts builds vocabulary and familiarity with grammatical structures." },
      { title: "Master Subordinate Clauses", description: "Latin relies heavily on subordinate clauses (cum, ut, qui, etc.). Practice recognizing clause types and translating them into natural English." },
      { title: "Know Roman Culture", description: "The exam tests Roman history, literature, and culture. Know major authors (Caesar, Cicero, Vergil), historical events, and cultural practices." },
      { title: "Practice Scansion", description: "For Vergil, practice scanning dactylic hexameter. Understanding meter helps with reading poetry and is tested on the exam." },
    ],
    faq: [
      { question: "Do I need to speak Latin?", answer: "No. AP Latin is a reading-based exam. Speaking and writing Latin are not tested, though they can help with comprehension." },
      { question: "How much vocabulary do I need?", answer: "The exam provides vocabulary lists, but you should know the most common words instinctively. Focus on high-frequency vocabulary through extensive reading." },
      { question: "Is the exam mostly Caesar and Vergil?", answer: "Yes, the syllabus focuses on Caesar's Gallic War and Vergil's Aeneid. Know these texts thoroughly, including style, themes, and historical context." },
    ],
    relatedSubjects: ["ap-english-literature", "ap-art-history", "ap-european-history", "ap-english-language"],
  },

  "ap-chinese-language": {
    slug: "ap-chinese-language",
    name: "AP Chinese Language",
    maxScore: 120,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ Part A (Listening)", maxScore: 40 },
      { name: "MCQ Part B (Reading)", maxScore: 40 },
      { name: "FRQ 1 (Conversation)", maxScore: 6 },
      { name: "FRQ 2 (Cultural Presentation)", maxScore: 6 },
      { name: "FRQ 3 (Email Response)", maxScore: 6 },
      { name: "FRQ 4 (Story Narration)", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "Part A: Listening comprehension, 40 questions",
      "Part B: Reading comprehension, 40 questions",
      "Section II: Free Response (50% of total score)",
      "Conversation, cultural presentation, email response, story narration",
      "Tests interpersonal, interpretive, and presentational communication",
      "Composite score out of 120",
    ],
    tips: [
      { title: "Master Tones", description: "Mandarin is tonal. Practice distinguishing and producing all four tones plus the neutral tone. Tone errors can change meaning completely." },
      { title: "Learn Characters Systematically", description: "Focus on high-frequency characters and radicals. Understanding radicals helps you guess meanings of unfamiliar characters." },
      { title: "Practice Simplified and Traditional", description: "The exam accepts both character systems. Choose one and master it, but be able to recognize the other in reading passages." },
      { title: "Know Chinese Culture Deeply", description: "The cultural presentation requires discussing Chinese customs, history, and society. Know major festivals, historical periods, and contemporary issues." },
    ],
    faq: [
      { question: "Do I need to know thousands of characters?", answer: "The exam tests approximately 500-600 characters for reading and writing. Focus on high-frequency characters used in everyday communication." },
      { question: "Is Pinyin tested?", answer: "Pinyin is used in the listening section and for typing responses, but the exam emphasizes characters. You should be comfortable reading characters without Pinyin." },
      { question: "How is the speaking section conducted?", answer: "You record spoken responses on computer. The conversation simulates real dialogue, and the cultural presentation is a 2-minute speech on a cultural topic." },
    ],
    relatedSubjects: ["ap-japanese-language", "ap-spanish-language", "ap-french-language", "ap-italian-language"],
  },

  "ap-japanese-language": {
    slug: "ap-japanese-language",
    name: "AP Japanese Language",
    maxScore: 120,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ Part A (Listening)", maxScore: 40 },
      { name: "MCQ Part B (Reading)", maxScore: 40 },
      { name: "FRQ 1 (Conversation)", maxScore: 6 },
      { name: "FRQ 2 (Cultural Presentation)", maxScore: 6 },
      { name: "FRQ 3 (Email Response)", maxScore: 6 },
      { name: "FRQ 4 (Text Chat)", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "Part A: Listening comprehension, 40 questions",
      "Part B: Reading comprehension, 40 questions",
      "Section II: Free Response (50% of total score)",
      "Conversation, cultural presentation, email response, text chat",
      "Tests interpersonal, interpretive, and presentational communication",
      "Composite score out of 120",
    ],
    tips: [
      { title: "Master Keigo (Honorifics)", description: "Japanese has complex honorific language (sonkeigo, kenjōgo, teineigo). Practice using appropriate speech levels for different social contexts." },
      { title: "Learn Kanji Systematically", description: "Focus on JLPT N4-N3 level kanji. Learn radicals and common components to help guess meanings of unfamiliar characters." },
      { title: "Practice Casual and Formal Speech", description: "The exam tests both casual (plain form) and formal (desu/masu) speech. Know when to use each and how to convert between them." },
      { title: "Understand Japanese Culture", description: "Know Japanese customs, social norms, and contemporary issues. The cultural presentation requires discussing Japanese practices in comparison with your own culture." },
    ],
    faq: [
      { question: "How many kanji do I need?", answer: "Approximately 300-400 kanji for the exam. Focus on high-frequency characters and practice reading them in context rather than in isolation." },
      { question: "Is Hiragana and Katakana enough?", answer: "No. While you must know both kana systems fluently, the exam requires kanji knowledge for reading comprehension and writing tasks." },
      { question: "How is the text chat different from email?", answer: "Text chat simulates informal digital communication with a peer. It requires casual language, abbreviations, and culturally appropriate responses in real-time format." },
    ],
    relatedSubjects: ["ap-chinese-language", "ap-spanish-language", "ap-french-language", "ap-italian-language"],
  },

  "ap-italian-language": {
    slug: "ap-italian-language",
    name: "AP Italian Language",
    maxScore: 100,
    mcqWeight: 50,
    frqWeight: 50,
    sections: [
      { name: "MCQ Part A (Reading)", maxScore: 30 },
      { name: "MCQ Part B (Listening)", maxScore: 35 },
      { name: "FRQ 1 (Email Reply)", maxScore: 6 },
      { name: "FRQ 2 (Argument Essay)", maxScore: 6 },
      { name: "FRQ 3 (Conversation)", maxScore: 6 },
      { name: "FRQ 4 (Cultural Comparison)", maxScore: 6 },
    ],
    scoringExplanation: [
      "Section I: Multiple Choice (50% of total score)",
      "Part A: Reading comprehension, 30 questions",
      "Part B: Listening comprehension, 35 questions",
      "Section II: Free Response (50% of total score)",
      "Email reply, persuasive essay, simulated conversation, cultural comparison",
      "Tests interpersonal, interpretive, and presentational communication",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Master Verb Conjugations", description: "Italian has many irregular verbs. Practice conjugating common verbs in all tenses, especially the subjunctive and conditional moods." },
      { title: "Understand Regional Variations", description: "Italy has significant regional diversity. Know differences between Northern and Southern Italian culture, dialects, and customs." },
      { title: "Practice Art and Culture Vocabulary", description: "Italian culture is deeply tied to art, music, and cuisine. Build vocabulary related to these topics for the cultural comparison and essay." },
      { title: "Know Italian History", description: "The unification of Italy, the Renaissance, and modern Italian politics appear in reading passages. Know key historical figures and events." },
    ],
    faq: [
      { question: "Is Italian easier than other Romance languages?", answer: "Italian pronunciation is very phonetic, which helps with speaking. However, verb conjugations and the subjunctive mood are complex and require extensive practice." },
      { question: "How important is cultural knowledge?", answer: "Very. The cultural comparison requires discussing Italian customs, history, and society. Know major Italian contributions to art, science, and politics." },
      { question: "Do I need to know dialects?", answer: "No, the exam tests Standard Italian. However, awareness of regional variations (e.g., Northern vs. Southern culture) can enrich your cultural comparisons." },
    ],
    relatedSubjects: ["ap-french-language", "ap-spanish-language", "ap-latin", "ap-german-language"],
  },

  "ap-research": {
    slug: "ap-research",
    name: "AP Research",
    maxScore: 100,
    mcqWeight: 0,
    frqWeight: 100,
    sections: [
      { name: "Academic Paper", maxScore: 75 },
      { name: "Presentation and Oral Defense", maxScore: 25 },
    ],
    scoringExplanation: [
      "AP Research is portfolio-based — no exam",
      "Academic Paper (75% of score)",
      "4,000-5,000 word research paper",
      "Must include literature review, methodology, data analysis, and conclusion",
      "Presentation and Oral Defense (25% of score)",
      "15-20 minute presentation",
      "Oral defense answering 3-4 questions from panel",
      "Scored on 1-5 scale by portfolio review",
    ],
    tips: [
      { title: "Choose a Narrow, Researchable Topic", description: "Your topic must be specific enough to research deeply but broad enough to find sources. Avoid topics that are too personal or subjective." },
      { title: "Start Research Early", description: "The literature review requires 15+ academic sources. Start searching databases (JSTOR, Google Scholar) at least 3 months before the deadline." },
      { title: "Use Appropriate Methodology", description: "Your research method (quantitative, qualitative, mixed) must match your research question. Explain why you chose your method and acknowledge limitations." },
      { title: "Practice Your Defense", description: "The oral defense tests your deep understanding of your research. Prepare for questions about methodology, limitations, and implications. Practice with teachers or peers." },
    ],
    faq: [
      { question: "Do I need to conduct original research?", answer: "Yes. Your paper must include original data collection or analysis. Pure literature reviews are not sufficient for AP Research." },
      { question: "How is the paper different from a typical essay?", answer: "It's a formal academic research paper with literature review, methodology section, data analysis, and APA citations. It should read like a journal article, not a high school essay." },
      { question: "Can I work with a partner?", answer: "No. AP Research is an individual project. You may consult teachers and peers, but the research, writing, and presentation must be your own work." },
    ],
    relatedSubjects: ["ap-seminar", "ap-english-language", "ap-statistics", "ap-psychology"],
  },

  "ap-seminar": {
    slug: "ap-seminar",
    name: "AP Seminar",
    maxScore: 100,
    mcqWeight: 0,
    frqWeight: 100,
    sections: [
      { name: "Team Project and Presentation", maxScore: 30 },
      { name: "Individual Research-Based Essay", maxScore: 35 },
      { name: "End-of-Course Exam", maxScore: 35 },
    ],
    scoringExplanation: [
      "AP Seminar is performance-based — no traditional exam",
      "Team Project and Presentation (30% of score)",
      "Group research on real-world topic",
      "Individual presentation with defense",
      "Individual Research-Based Essay (35% of score)",
      "2,000 word essay using provided sources",
      "End-of-Course Exam (35% of score)",
      "3 short-answer questions analyzing sources",
      "1 essay synthesizing multiple perspectives",
      "Composite score out of 100",
    ],
    tips: [
      { title: "Collaborate Effectively", description: "The team project requires genuine collaboration. Divide work fairly, communicate regularly, and hold each other accountable for deadlines." },
      { title: "Evaluate Sources Critically", description: "Seminar emphasizes source evaluation. Practice identifying bias, assessing credibility, and comparing perspectives across sources." },
      { title: "Synthesize Multiple Perspectives", description: "The exam and essay require synthesizing conflicting viewpoints. Practice finding common ground and acknowledging complexity rather than taking simple positions." },
      { title: "Develop Your Argument", description: "Your presentations and essays need clear, evidence-based arguments. Practice stating claims, providing evidence, and explaining reasoning explicitly." },
    ],
    faq: [
      { question: "Is Seminar easier than Research?", answer: "Seminar is typically taken before Research and introduces academic skills. Many students find it more structured and manageable than the independent Research project." },
      { question: "How is the team project scored?", answer: "You receive both a team score (for the overall project) and an individual score (for your presentation and reflection). Your individual score is what counts for AP." },
      { question: "What topics can we choose?", answer: "Topics are broad real-world issues (e.g., technology and privacy, education equity, environmental policy). Your teacher may provide options or let you choose within guidelines." },
    ],
    relatedSubjects: ["ap-research", "ap-english-language", "ap-psychology", "ap-us-government"],
  },
};

export function getSubjectConfig(slug: string): SubjectConfig | undefined {
  return SUBJECT_CONFIGS[slug];
}

export function getAllSubjectSlugs(): string[] {
  return Object.keys(SUBJECT_CONFIGS);
}
